/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AudioBlob {
  'url' : string,
  'status' : AudioStatus,
  'blobType' : { 'internal' : null } |
    { 'external' : null },
  'blobId' : string,
}
export type AudioStatus = { 'notStarted' : null } |
  { 'processing' : null } |
  { 'ready' : null } |
  { 'failed' : null };
export interface AudioValidationResult {
  'audioUrl' : [] | [string],
  'error' : [] | [string],
  'input' : string,
  'isValid' : boolean,
}
export type DownloadLink = string;
export type ExternalBlob = Uint8Array;
export interface FileContent {
  'content' : string,
  'path' : string,
  'lastModified' : bigint,
}
export interface FileMetadata {
  'canWrite' : boolean,
  'path' : string,
  'size' : bigint,
  'lastModified' : bigint,
  'isDirectory' : boolean,
}
export interface FileSaveResult {
  'path' : string,
  'message' : string,
  'timestamp' : bigint,
  'success' : boolean,
}
export interface FileTreeNode {
  'canWrite' : boolean,
  'name' : string,
  'path' : string,
  'children' : Array<FileTreeNode>,
  'isDirectory' : boolean,
}
export interface Metadata {
  'tags' : Array<string>,
  'hookLines' : Array<string>,
  'description' : string,
}
export type MusicTrack = string;
export type NarrationText = string;
export type Niche = string;
export interface PartialProject {
  'status' : ProjectStatus,
  'music' : MusicTrack,
  'shorts' : Array<Segment>,
  'audio' : AudioBlob,
  'shortsLink' : DownloadLink,
  'owner' : Principal,
  'metadata' : Metadata,
  'script' : Script,
  'shortsFiles' : Array<ExternalBlob>,
  'fullVideoLink' : DownloadLink,
  'error' : [] | [string],
  'progress' : bigint,
  'narration' : NarrationText,
  'originalVideo' : [] | [ExternalBlob],
  'projectId' : string,
  'niche' : Niche,
  'length' : VideoLength,
  'videos' : Array<VideoClip>,
  'subtitles' : Array<Subtitle>,
}
export type Principal = Principal;
export type ProjectStatus = { 'videoMerging' : null } |
  { 'scripting' : null } |
  { 'completed' : null } |
  { 'finalizing' : null } |
  { 'error' : null } |
  { 'audioRendering' : null };
export type Script = string;
export type Segment = string;
export type Subtitle = string;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface TtsLogEntry {
  'id' : bigint,
  'status' : { 'started' : null } |
    { 'error' : null } |
    { 'success' : null },
  'ttsService' : TtsService,
  'audioUrl' : [] | [string],
  'errorCode' : [] | [bigint],
  'message' : string,
  'timestamp' : bigint,
  'mp3Generated' : boolean,
  'integrityConfirmed' : boolean,
}
export type TtsService = { 'edge' : null } |
  { 'gtts' : null } |
  { 'openAccess' : null } |
  { 'local' : null } |
  { 'huggingFace' : null };
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'preferences' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VideoClip = string;
export type VideoLength = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cleanScript' : ActorMethod<[string], string>,
  'createProject' : ActorMethod<[VideoLength, Niche], string>,
  'deleteProject' : ActorMethod<[string], boolean>,
  'finalizeProject' : ActorMethod<
    [
      string,
      DownloadLink,
      DownloadLink,
      Array<Segment>,
      ExternalBlob,
      Array<ExternalBlob>,
    ],
    undefined
  >,
  'getAllTtsLogs' : ActorMethod<[], Array<TtsLogEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFileMetadata' : ActorMethod<[string], [] | [FileMetadata]>,
  'getFileTree' : ActorMethod<[string], Array<FileTreeNode>>,
  'getPagedProjects' : ActorMethod<[bigint, bigint], Array<PartialProject>>,
  'getProgressPercentage' : ActorMethod<[string], bigint>,
  'getProjectDownloadLinks' : ActorMethod<
    [string],
    [DownloadLink, DownloadLink]
  >,
  'getProjectStatus' : ActorMethod<[string], ProjectStatus>,
  'getProjectsByStatus' : ActorMethod<[ProjectStatus], Array<PartialProject>>,
  'getStatistics' : ActorMethod<
    [],
    {
      'completed' : bigint,
      'totalProjects' : bigint,
      'avgProgress' : bigint,
      'byStatus' : Array<[ProjectStatus, bigint]>,
    }
  >,
  'getTtsLogsByService' : ActorMethod<[TtsService], Array<TtsLogEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'handleApiError' : ActorMethod<[string, string], undefined>,
  'integrateHuggingFaceTts' : ActorMethod<[string, string], AudioBlob>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logTtsEvent' : ActorMethod<
    [
      TtsService,
      { 'started' : null } |
        { 'error' : null } |
        { 'success' : null },
      string,
      [] | [bigint],
      boolean,
      [] | [string],
      boolean,
    ],
    undefined
  >,
  'readFile' : ActorMethod<[string], [] | [FileContent]>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveFile' : ActorMethod<[string, string], FileSaveResult>,
  'toggleTestMode' : ActorMethod<[], boolean>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAudio' : ActorMethod<[string, AudioBlob, MusicTrack], undefined>,
  'updateAudioUrl' : ActorMethod<[string, string], AudioValidationResult>,
  'updateScript' : ActorMethod<
    [string, Script, Metadata, NarrationText],
    undefined
  >,
  'updateVideos' : ActorMethod<
    [string, Array<VideoClip>, Array<Subtitle>],
    undefined
  >,
  'validateAudioUrl' : ActorMethod<[string], AudioValidationResult>,
  'validateEnvFile' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];