/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface FileContent {
    content: string;
    path: string;
    lastModified: bigint;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface AudioValidationResult {
    audioUrl?: string;
    error?: string;
    input: string;
    isValid: boolean;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface FileSaveResult {
    path: string;
    message: string;
    timestamp: bigint;
    success: boolean;
}
export interface AudioBlob {
    url: string;
    status: AudioStatus;
    blobType: Variant_internal_external;
    blobId: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type NarrationText = string;
export interface TtsLogEntry {
    id: bigint;
    status: Variant_started_error_success;
    ttsService: TtsService;
    audioUrl?: string;
    errorCode?: bigint;
    message: string;
    timestamp: bigint;
    mp3Generated: boolean;
    integrityConfirmed: boolean;
}
export interface PartialProject {
    status: ProjectStatus;
    music: MusicTrack;
    shorts: Array<Segment>;
    audio: AudioBlob;
    shortsLink: DownloadLink;
    owner: Principal;
    metadata: Metadata;
    script: Script;
    shortsFiles: Array<ExternalBlob>;
    fullVideoLink: DownloadLink;
    error?: string;
    progress: bigint;
    narration: NarrationText;
    originalVideo?: ExternalBlob;
    projectId: string;
    niche: Niche;
    length: VideoLength;
    videos: Array<VideoClip>;
    subtitles: Array<Subtitle>;
}
export type Niche = string;
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type Script = string;
export type VideoLength = bigint;
export type MusicTrack = string;
export type Segment = string;
export interface FileMetadata {
    canWrite: boolean;
    path: string;
    size: bigint;
    lastModified: bigint;
    isDirectory: boolean;
}
export type VideoClip = string;
export type Principal = Principal;
export interface FileTreeNode {
    canWrite: boolean;
    name: string;
    path: string;
    children: Array<FileTreeNode>;
    isDirectory: boolean;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface Metadata {
    tags: Array<string>;
    hookLines: Array<string>;
    description: string;
}
export type DownloadLink = string;
export type Subtitle = string;
export interface UserProfile {
    name: string;
    email?: string;
    preferences?: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum AudioStatus {
    notStarted = "notStarted",
    processing = "processing",
    ready = "ready",
    failed = "failed"
}
export enum ProjectStatus {
    videoMerging = "videoMerging",
    scripting = "scripting",
    completed = "completed",
    finalizing = "finalizing",
    error = "error",
    audioRendering = "audioRendering"
}
export enum TtsService {
    edge = "edge",
    gtts = "gtts",
    openAccess = "openAccess",
    local = "local",
    huggingFace = "huggingFace"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_internal_external {
    internal = "internal",
    external = "external"
}
export enum Variant_started_error_success {
    started = "started",
    error = "error",
    success = "success"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cleanScript(script: string): Promise<string>;
    createProject(length: VideoLength, niche: Niche): Promise<string>;
    deleteProject(projectId: string): Promise<boolean>;
    finalizeProject(projectId: string, fullVideoLink: DownloadLink, shortsLink: DownloadLink, shorts: Array<Segment>, originalVideo: ExternalBlob, shortsFiles: Array<ExternalBlob>): Promise<void>;
    getAllTtsLogs(): Promise<Array<TtsLogEntry>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFileMetadata(path: string): Promise<FileMetadata | null>;
    getFileTree(rootPath: string): Promise<Array<FileTreeNode>>;
    getPagedProjects(pageSize: bigint, pageIndex: bigint): Promise<Array<PartialProject>>;
    getProgressPercentage(projectId: string): Promise<bigint>;
    getProjectDownloadLinks(projectId: string): Promise<[DownloadLink, DownloadLink]>;
    getProjectStatus(projectId: string): Promise<ProjectStatus>;
    getProjectsByStatus(status: ProjectStatus): Promise<Array<PartialProject>>;
    getStatistics(): Promise<{
        completed: bigint;
        totalProjects: bigint;
        avgProgress: bigint;
        byStatus: Array<[ProjectStatus, bigint]>;
    }>;
    getTtsLogsByService(service: TtsService): Promise<Array<TtsLogEntry>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    handleApiError(projectId: string, errorMessage: string): Promise<void>;
    integrateHuggingFaceTts(projectId: string, narration: string): Promise<AudioBlob>;
    isCallerAdmin(): Promise<boolean>;
    logTtsEvent(ttsService: TtsService, status: Variant_started_error_success, message: string, errorCode: bigint | null, mp3Generated: boolean, audioUrl: string | null, integrityConfirmed: boolean): Promise<void>;
    readFile(path: string): Promise<FileContent | null>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveFile(path: string, content: string): Promise<FileSaveResult>;
    toggleTestMode(): Promise<boolean>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateAudio(projectId: string, audio: AudioBlob, music: MusicTrack): Promise<void>;
    updateAudioUrl(projectId: string, url: string): Promise<AudioValidationResult>;
    updateScript(projectId: string, script: Script, metadata: Metadata, narration: NarrationText): Promise<void>;
    updateVideos(projectId: string, videos: Array<VideoClip>, subtitles: Array<Subtitle>): Promise<void>;
    validateAudioUrl(url: string): Promise<AudioValidationResult>;
    validateEnvFile(content: string): Promise<boolean>;
}
import type { AudioBlob as _AudioBlob, AudioStatus as _AudioStatus, AudioValidationResult as _AudioValidationResult, DownloadLink as _DownloadLink, ExternalBlob as _ExternalBlob, FileContent as _FileContent, FileMetadata as _FileMetadata, FileTreeNode as _FileTreeNode, Metadata as _Metadata, MusicTrack as _MusicTrack, NarrationText as _NarrationText, Niche as _Niche, PartialProject as _PartialProject, Principal as _Principal, ProjectStatus as _ProjectStatus, Script as _Script, Segment as _Segment, Subtitle as _Subtitle, TtsLogEntry as _TtsLogEntry, TtsService as _TtsService, UserProfile as _UserProfile, UserRole as _UserRole, VideoClip as _VideoClip, VideoLength as _VideoLength, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async cleanScript(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.cleanScript(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cleanScript(arg0);
            return result;
        }
    }
    async createProject(arg0: VideoLength, arg1: Niche): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(arg0, arg1);
            return result;
        }
    }
    async deleteProject(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async finalizeProject(arg0: string, arg1: DownloadLink, arg2: DownloadLink, arg3: Array<Segment>, arg4: ExternalBlob, arg5: Array<ExternalBlob>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.finalizeProject(arg0, arg1, arg2, arg3, await to_candid_ExternalBlob_n10(this.uploadFile, this.downloadFile, arg4), await to_candid_vec_n11(this.uploadFile, this.downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.finalizeProject(arg0, arg1, arg2, arg3, await to_candid_ExternalBlob_n10(this.uploadFile, this.downloadFile, arg4), await to_candid_vec_n11(this.uploadFile, this.downloadFile, arg5));
            return result;
        }
    }
    async getAllTtsLogs(): Promise<Array<TtsLogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTtsLogs();
                return from_candid_vec_n12(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTtsLogs();
            return from_candid_vec_n12(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n19(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n19(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n22(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n22(this.uploadFile, this.downloadFile, result);
        }
    }
    async getFileMetadata(arg0: string): Promise<FileMetadata | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFileMetadata(arg0);
                return from_candid_opt_n24(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFileMetadata(arg0);
            return from_candid_opt_n24(this.uploadFile, this.downloadFile, result);
        }
    }
    async getFileTree(arg0: string): Promise<Array<FileTreeNode>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFileTree(arg0);
                return from_candid_vec_n25(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFileTree(arg0);
            return from_candid_vec_n25(this.uploadFile, this.downloadFile, result);
        }
    }
    async getPagedProjects(arg0: bigint, arg1: bigint): Promise<Array<PartialProject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPagedProjects(arg0, arg1);
                return from_candid_vec_n28(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPagedProjects(arg0, arg1);
            return from_candid_vec_n28(this.uploadFile, this.downloadFile, result);
        }
    }
    async getProgressPercentage(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getProgressPercentage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProgressPercentage(arg0);
            return result;
        }
    }
    async getProjectDownloadLinks(arg0: string): Promise<[DownloadLink, DownloadLink]> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectDownloadLinks(arg0);
                return [
                    result[0],
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectDownloadLinks(arg0);
            return [
                result[0],
                result[1]
            ];
        }
    }
    async getProjectStatus(arg0: string): Promise<ProjectStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectStatus(arg0);
                return from_candid_ProjectStatus_n31(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectStatus(arg0);
            return from_candid_ProjectStatus_n31(this.uploadFile, this.downloadFile, result);
        }
    }
    async getProjectsByStatus(arg0: ProjectStatus): Promise<Array<PartialProject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectsByStatus(to_candid_ProjectStatus_n41(this.uploadFile, this.downloadFile, arg0));
                return from_candid_vec_n28(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectsByStatus(to_candid_ProjectStatus_n41(this.uploadFile, this.downloadFile, arg0));
            return from_candid_vec_n28(this.uploadFile, this.downloadFile, result);
        }
    }
    async getStatistics(): Promise<{
        completed: bigint;
        totalProjects: bigint;
        avgProgress: bigint;
        byStatus: Array<[ProjectStatus, bigint]>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getStatistics();
                return from_candid_record_n43(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStatistics();
            return from_candid_record_n43(this.uploadFile, this.downloadFile, result);
        }
    }
    async getTtsLogsByService(arg0: TtsService): Promise<Array<TtsLogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTtsLogsByService(to_candid_TtsService_n46(this.uploadFile, this.downloadFile, arg0));
                return from_candid_vec_n12(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTtsLogsByService(to_candid_TtsService_n46(this.uploadFile, this.downloadFile, arg0));
            return from_candid_vec_n12(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n19(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n19(this.uploadFile, this.downloadFile, result);
        }
    }
    async handleApiError(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.handleApiError(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.handleApiError(arg0, arg1);
            return result;
        }
    }
    async integrateHuggingFaceTts(arg0: string, arg1: string): Promise<AudioBlob> {
        if (this.processError) {
            try {
                const result = await this.actor.integrateHuggingFaceTts(arg0, arg1);
                return from_candid_AudioBlob_n33(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.integrateHuggingFaceTts(arg0, arg1);
            return from_candid_AudioBlob_n33(this.uploadFile, this.downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async logTtsEvent(arg0: TtsService, arg1: Variant_started_error_success, arg2: string, arg3: bigint | null, arg4: boolean, arg5: string | null, arg6: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logTtsEvent(to_candid_TtsService_n46(this.uploadFile, this.downloadFile, arg0), to_candid_variant_n48(this.uploadFile, this.downloadFile, arg1), arg2, to_candid_opt_n49(this.uploadFile, this.downloadFile, arg3), arg4, to_candid_opt_n50(this.uploadFile, this.downloadFile, arg5), arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logTtsEvent(to_candid_TtsService_n46(this.uploadFile, this.downloadFile, arg0), to_candid_variant_n48(this.uploadFile, this.downloadFile, arg1), arg2, to_candid_opt_n49(this.uploadFile, this.downloadFile, arg3), arg4, to_candid_opt_n50(this.uploadFile, this.downloadFile, arg5), arg6);
            return result;
        }
    }
    async readFile(arg0: string): Promise<FileContent | null> {
        if (this.processError) {
            try {
                const result = await this.actor.readFile(arg0);
                return from_candid_opt_n51(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.readFile(arg0);
            return from_candid_opt_n51(this.uploadFile, this.downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n52(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n52(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async saveFile(arg0: string, arg1: string): Promise<FileSaveResult> {
        if (this.processError) {
            try {
                const result = await this.actor.saveFile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveFile(arg0, arg1);
            return result;
        }
    }
    async toggleTestMode(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleTestMode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleTestMode();
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateAudio(arg0: string, arg1: AudioBlob, arg2: MusicTrack): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAudio(arg0, to_candid_AudioBlob_n54(this.uploadFile, this.downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAudio(arg0, to_candid_AudioBlob_n54(this.uploadFile, this.downloadFile, arg1), arg2);
            return result;
        }
    }
    async updateAudioUrl(arg0: string, arg1: string): Promise<AudioValidationResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAudioUrl(arg0, arg1);
                return from_candid_AudioValidationResult_n59(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAudioUrl(arg0, arg1);
            return from_candid_AudioValidationResult_n59(this.uploadFile, this.downloadFile, result);
        }
    }
    async updateScript(arg0: string, arg1: Script, arg2: Metadata, arg3: NarrationText): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateScript(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateScript(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateVideos(arg0: string, arg1: Array<VideoClip>, arg2: Array<Subtitle>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVideos(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVideos(arg0, arg1, arg2);
            return result;
        }
    }
    async validateAudioUrl(arg0: string): Promise<AudioValidationResult> {
        if (this.processError) {
            try {
                const result = await this.actor.validateAudioUrl(arg0);
                return from_candid_AudioValidationResult_n59(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateAudioUrl(arg0);
            return from_candid_AudioValidationResult_n59(this.uploadFile, this.downloadFile, result);
        }
    }
    async validateEnvFile(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.validateEnvFile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateEnvFile(arg0);
            return result;
        }
    }
}
function from_candid_AudioBlob_n33(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AudioBlob): AudioBlob {
    return from_candid_record_n34(uploadFile, downloadFile, value);
}
function from_candid_AudioStatus_n35(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AudioStatus): AudioStatus {
    return from_candid_variant_n36(uploadFile, downloadFile, value);
}
function from_candid_AudioValidationResult_n59(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AudioValidationResult): AudioValidationResult {
    return from_candid_record_n60(uploadFile, downloadFile, value);
}
async function from_candid_ExternalBlob_n39(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await downloadFile(value);
}
function from_candid_FileTreeNode_n26(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FileTreeNode): FileTreeNode {
    return from_candid_record_n27(uploadFile, downloadFile, value);
}
async function from_candid_PartialProject_n29(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PartialProject): Promise<PartialProject> {
    return await from_candid_record_n30(uploadFile, downloadFile, value);
}
function from_candid_ProjectStatus_n31(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectStatus): ProjectStatus {
    return from_candid_variant_n32(uploadFile, downloadFile, value);
}
function from_candid_TtsLogEntry_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TtsLogEntry): TtsLogEntry {
    return from_candid_record_n14(uploadFile, downloadFile, value);
}
function from_candid_TtsService_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TtsService): TtsService {
    return from_candid_variant_n17(uploadFile, downloadFile, value);
}
function from_candid_UserProfile_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n21(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n23(uploadFile, downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(uploadFile, downloadFile, value);
}
function from_candid_opt_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n20(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FileMetadata]): FileMetadata | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n40(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n39(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n51(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FileContent]): FileContent | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: {
        started: null;
    } | {
        error: null;
    } | {
        success: null;
    };
    ttsService: _TtsService;
    audioUrl: [] | [string];
    errorCode: [] | [bigint];
    message: string;
    timestamp: bigint;
    mp3Generated: boolean;
    integrityConfirmed: boolean;
}): {
    id: bigint;
    status: Variant_started_error_success;
    ttsService: TtsService;
    audioUrl?: string;
    errorCode?: bigint;
    message: string;
    timestamp: bigint;
    mp3Generated: boolean;
    integrityConfirmed: boolean;
} {
    return {
        id: value.id,
        status: from_candid_variant_n15(uploadFile, downloadFile, value.status),
        ttsService: from_candid_TtsService_n16(uploadFile, downloadFile, value.ttsService),
        audioUrl: record_opt_to_undefined(from_candid_opt_n18(uploadFile, downloadFile, value.audioUrl)),
        errorCode: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.errorCode)),
        message: value.message,
        timestamp: value.timestamp,
        mp3Generated: value.mp3Generated,
        integrityConfirmed: value.integrityConfirmed
    };
}
function from_candid_record_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: [] | [string];
    preferences: [] | [string];
}): {
    name: string;
    email?: string;
    preferences?: string;
} {
    return {
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n18(uploadFile, downloadFile, value.email)),
        preferences: record_opt_to_undefined(from_candid_opt_n18(uploadFile, downloadFile, value.preferences))
    };
}
function from_candid_record_n27(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    canWrite: boolean;
    name: string;
    path: string;
    children: Array<_FileTreeNode>;
    isDirectory: boolean;
}): {
    canWrite: boolean;
    name: string;
    path: string;
    children: Array<FileTreeNode>;
    isDirectory: boolean;
} {
    return {
        canWrite: value.canWrite,
        name: value.name,
        path: value.path,
        children: from_candid_vec_n25(uploadFile, downloadFile, value.children),
        isDirectory: value.isDirectory
    };
}
async function from_candid_record_n30(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ProjectStatus;
    music: _MusicTrack;
    shorts: Array<_Segment>;
    audio: _AudioBlob;
    shortsLink: _DownloadLink;
    owner: _Principal;
    metadata: _Metadata;
    script: _Script;
    shortsFiles: Array<_ExternalBlob>;
    fullVideoLink: _DownloadLink;
    error: [] | [string];
    progress: bigint;
    narration: _NarrationText;
    originalVideo: [] | [_ExternalBlob];
    projectId: string;
    niche: _Niche;
    length: _VideoLength;
    videos: Array<_VideoClip>;
    subtitles: Array<_Subtitle>;
}): Promise<{
    status: ProjectStatus;
    music: MusicTrack;
    shorts: Array<Segment>;
    audio: AudioBlob;
    shortsLink: DownloadLink;
    owner: Principal;
    metadata: Metadata;
    script: Script;
    shortsFiles: Array<ExternalBlob>;
    fullVideoLink: DownloadLink;
    error?: string;
    progress: bigint;
    narration: NarrationText;
    originalVideo?: ExternalBlob;
    projectId: string;
    niche: Niche;
    length: VideoLength;
    videos: Array<VideoClip>;
    subtitles: Array<Subtitle>;
}> {
    return {
        status: from_candid_ProjectStatus_n31(uploadFile, downloadFile, value.status),
        music: value.music,
        shorts: value.shorts,
        audio: from_candid_AudioBlob_n33(uploadFile, downloadFile, value.audio),
        shortsLink: value.shortsLink,
        owner: value.owner,
        metadata: value.metadata,
        script: value.script,
        shortsFiles: await from_candid_vec_n38(uploadFile, downloadFile, value.shortsFiles),
        fullVideoLink: value.fullVideoLink,
        error: record_opt_to_undefined(from_candid_opt_n18(uploadFile, downloadFile, value.error)),
        progress: value.progress,
        narration: value.narration,
        originalVideo: record_opt_to_undefined(await from_candid_opt_n40(uploadFile, downloadFile, value.originalVideo)),
        projectId: value.projectId,
        niche: value.niche,
        length: value.length,
        videos: value.videos,
        subtitles: value.subtitles
    };
}
function from_candid_record_n34(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    url: string;
    status: _AudioStatus;
    blobType: {
        internal: null;
    } | {
        external: null;
    };
    blobId: string;
}): {
    url: string;
    status: AudioStatus;
    blobType: Variant_internal_external;
    blobId: string;
} {
    return {
        url: value.url,
        status: from_candid_AudioStatus_n35(uploadFile, downloadFile, value.status),
        blobType: from_candid_variant_n37(uploadFile, downloadFile, value.blobType),
        blobId: value.blobId
    };
}
function from_candid_record_n43(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: bigint;
    totalProjects: bigint;
    avgProgress: bigint;
    byStatus: Array<[_ProjectStatus, bigint]>;
}): {
    completed: bigint;
    totalProjects: bigint;
    avgProgress: bigint;
    byStatus: Array<[ProjectStatus, bigint]>;
} {
    return {
        completed: value.completed,
        totalProjects: value.totalProjects,
        avgProgress: value.avgProgress,
        byStatus: from_candid_vec_n44(uploadFile, downloadFile, value.byStatus)
    };
}
function from_candid_record_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(uploadFile, downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n60(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    audioUrl: [] | [string];
    error: [] | [string];
    input: string;
    isValid: boolean;
}): {
    audioUrl?: string;
    error?: string;
    input: string;
    isValid: boolean;
} {
    return {
        audioUrl: record_opt_to_undefined(from_candid_opt_n18(uploadFile, downloadFile, value.audioUrl)),
        error: record_opt_to_undefined(from_candid_opt_n18(uploadFile, downloadFile, value.error)),
        input: value.input,
        isValid: value.isValid
    };
}
function from_candid_tuple_n45(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_ProjectStatus, bigint]): [ProjectStatus, bigint] {
    return [
        from_candid_ProjectStatus_n31(uploadFile, downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    started: null;
} | {
    error: null;
} | {
    success: null;
}): Variant_started_error_success {
    return "started" in value ? Variant_started_error_success.started : "error" in value ? Variant_started_error_success.error : "success" in value ? Variant_started_error_success.success : value;
}
function from_candid_variant_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    edge: null;
} | {
    gtts: null;
} | {
    openAccess: null;
} | {
    local: null;
} | {
    huggingFace: null;
}): TtsService {
    return "edge" in value ? TtsService.edge : "gtts" in value ? TtsService.gtts : "openAccess" in value ? TtsService.openAccess : "local" in value ? TtsService.local : "huggingFace" in value ? TtsService.huggingFace : value;
}
function from_candid_variant_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n32(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    videoMerging: null;
} | {
    scripting: null;
} | {
    completed: null;
} | {
    finalizing: null;
} | {
    error: null;
} | {
    audioRendering: null;
}): ProjectStatus {
    return "videoMerging" in value ? ProjectStatus.videoMerging : "scripting" in value ? ProjectStatus.scripting : "completed" in value ? ProjectStatus.completed : "finalizing" in value ? ProjectStatus.finalizing : "error" in value ? ProjectStatus.error : "audioRendering" in value ? ProjectStatus.audioRendering : value;
}
function from_candid_variant_n36(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notStarted: null;
} | {
    processing: null;
} | {
    ready: null;
} | {
    failed: null;
}): AudioStatus {
    return "notStarted" in value ? AudioStatus.notStarted : "processing" in value ? AudioStatus.processing : "ready" in value ? AudioStatus.ready : "failed" in value ? AudioStatus.failed : value;
}
function from_candid_variant_n37(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    internal: null;
} | {
    external: null;
}): Variant_internal_external {
    return "internal" in value ? Variant_internal_external.internal : "external" in value ? Variant_internal_external.external : value;
}
function from_candid_vec_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TtsLogEntry>): Array<TtsLogEntry> {
    return value.map((x)=>from_candid_TtsLogEntry_n13(uploadFile, downloadFile, x));
}
function from_candid_vec_n25(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FileTreeNode>): Array<FileTreeNode> {
    return value.map((x)=>from_candid_FileTreeNode_n26(uploadFile, downloadFile, x));
}
async function from_candid_vec_n28(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PartialProject>): Promise<Array<PartialProject>> {
    return await Promise.all(value.map(async (x)=>await from_candid_PartialProject_n29(uploadFile, downloadFile, x)));
}
async function from_candid_vec_n38(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n39(uploadFile, downloadFile, x)));
}
function from_candid_vec_n44(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_ProjectStatus, bigint]>): Array<[ProjectStatus, bigint]> {
    return value.map((x)=>from_candid_tuple_n45(uploadFile, downloadFile, x));
}
function to_candid_AudioBlob_n54(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AudioBlob): _AudioBlob {
    return to_candid_record_n55(uploadFile, downloadFile, value);
}
function to_candid_AudioStatus_n56(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AudioStatus): _AudioStatus {
    return to_candid_variant_n57(uploadFile, downloadFile, value);
}
async function to_candid_ExternalBlob_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await uploadFile(value);
}
function to_candid_ProjectStatus_n41(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStatus): _ProjectStatus {
    return to_candid_variant_n42(uploadFile, downloadFile, value);
}
function to_candid_TtsService_n46(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TtsService): _TtsService {
    return to_candid_variant_n47(uploadFile, downloadFile, value);
}
function to_candid_UserProfile_n52(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n53(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(uploadFile, downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(uploadFile, downloadFile, value);
}
function to_candid_opt_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(uploadFile, downloadFile, value));
}
function to_candid_opt_n49(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n50(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n53(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email?: string;
    preferences?: string;
}): {
    name: string;
    email: [] | [string];
    preferences: [] | [string];
} {
    return {
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none(),
        preferences: value.preferences ? candid_some(value.preferences) : candid_none()
    };
}
function to_candid_record_n55(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    url: string;
    status: AudioStatus;
    blobType: Variant_internal_external;
    blobId: string;
}): {
    url: string;
    status: _AudioStatus;
    blobType: {
        internal: null;
    } | {
        external: null;
    };
    blobId: string;
} {
    return {
        url: value.url,
        status: to_candid_AudioStatus_n56(uploadFile, downloadFile, value.status),
        blobType: to_candid_variant_n58(uploadFile, downloadFile, value.blobType),
        blobId: value.blobId
    };
}
function to_candid_variant_n42(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStatus): {
    videoMerging: null;
} | {
    scripting: null;
} | {
    completed: null;
} | {
    finalizing: null;
} | {
    error: null;
} | {
    audioRendering: null;
} {
    return value == ProjectStatus.videoMerging ? {
        videoMerging: null
    } : value == ProjectStatus.scripting ? {
        scripting: null
    } : value == ProjectStatus.completed ? {
        completed: null
    } : value == ProjectStatus.finalizing ? {
        finalizing: null
    } : value == ProjectStatus.error ? {
        error: null
    } : value == ProjectStatus.audioRendering ? {
        audioRendering: null
    } : value;
}
function to_candid_variant_n47(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TtsService): {
    edge: null;
} | {
    gtts: null;
} | {
    openAccess: null;
} | {
    local: null;
} | {
    huggingFace: null;
} {
    return value == TtsService.edge ? {
        edge: null
    } : value == TtsService.gtts ? {
        gtts: null
    } : value == TtsService.openAccess ? {
        openAccess: null
    } : value == TtsService.local ? {
        local: null
    } : value == TtsService.huggingFace ? {
        huggingFace: null
    } : value;
}
function to_candid_variant_n48(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_started_error_success): {
    started: null;
} | {
    error: null;
} | {
    success: null;
} {
    return value == Variant_started_error_success.started ? {
        started: null
    } : value == Variant_started_error_success.error ? {
        error: null
    } : value == Variant_started_error_success.success ? {
        success: null
    } : value;
}
function to_candid_variant_n57(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AudioStatus): {
    notStarted: null;
} | {
    processing: null;
} | {
    ready: null;
} | {
    failed: null;
} {
    return value == AudioStatus.notStarted ? {
        notStarted: null
    } : value == AudioStatus.processing ? {
        processing: null
    } : value == AudioStatus.ready ? {
        ready: null
    } : value == AudioStatus.failed ? {
        failed: null
    } : value;
}
function to_candid_variant_n58(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_internal_external): {
    internal: null;
} | {
    external: null;
} {
    return value == Variant_internal_external.internal ? {
        internal: null
    } : value == Variant_internal_external.external ? {
        external: null
    } : value;
}
function to_candid_variant_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n10(uploadFile, downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
